<!DOCTYPE html>
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="de"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="de"> <!--<![endif]-->
    <head>
        <!-- Open Graph :: Start -->
        <script type="application/x-moraso" src="HTML.Meta.Open.Graph">
            site_name = "moraso CMS"
            title_suffix = " | moraso CMS"
        </script>
        <!-- Open Graph :: End -->
    </head>
    <body>
        <!-- Google Tag Manager -->
        <script type="application/x-moraso" src="Google.Tag.Manager">
            container = XYZ-123
        </script>
        <!-- End Google Tag Manager -->

        <!-- Header :: Start -->
        <header id="header">
            <div class="row">
                <div class="large-12 columns">
                    <script type="application/x-moraso" src="Template:Header">
                        defaultTemplate = default

                        template.default.name = Standard
                        template.default.file = templates/header/default.phtml 
                    </script>
                </div>
            </div>
        </header>
        <!-- Header :: End -->

        <!-- Content :: Start -->
        <div class="row" role="main">
            <div id="page-wrapper" class="large-12 columns">
                <script type="application/x-moraso" src="Template:Main">
                    defaultTemplate = default

                    template.default.name = Standard
                    template.default.file = templates/main/default.phtml 

                    template.start.name = Start
                    template.start.file = templates/main/start.phtml 
                </script>
            </div>
        </div>
        <!-- Content :: End -->

        <!-- Footer :: Start -->
        <footer id="footer">
            <div class="row">
                <div class="large-12 columns">
                    <script type="application/x-moraso" src="Template:Footer">
                        defaultTemplate = default

                        template.default.name = Standard
                        template.default.file = templates/footer/default.phtml 
                    </script>
                </div>
            </div>
        </footer>
        <!-- Footer :: End -->
    </body>
</html>
