var dashboard = Ext.getCmp('dashboard');

var store = new Ext.data.JsonStore({
		        autoDestroy: true,
		        url: '<?php echo $this->url(array('paction' => 'store')); ?>',
		        root: 'data',
		        fields: [{
		            name: 'idevent',
                            type: 'int'
		        }, {
		            name: 'title'
		        }, {
		            name: 'text'
		        }, {
		            name: 'organizer'
		        }, {
                            name: 'starttime',
                            type: 'date',
                            dateFormat: 'Y-m-d H:i:s'
                        }, {
                            name: 'endtime',
                            type: 'date',
                            dateFormat: 'Y-m-d H:i:s'
                        }]
		    });
                    
var eventExpander = new Ext.ux.grid.RowExpander({
    tpl : new Ext.Template(
        '<pre style="padding:10px;">{text}</pre>'
    )
});

var editEvent = function(idevent) {
    Ext.aitsu.load(['<?php echo $this->url(array('area' => 'management', 'plugin' => 'events', 'paction' => 'index'), 'plugin'); ?>']);
    
    Ext.aitsu.load(['<?php echo $this->url(array('area' => 'management', 'plugin' => 'events', 'paction' => 'edit'), 'plugin'); ?>'], null, {
        idevent: idevent
    });
}

var events = new Ext.grid.GridPanel({
    id: 'events',
    title: 'Events',
    store: store,
    sortInfo: {
        field: 'created',
        direction: 'ASC'
    },
    columns: [
    	eventExpander,
        {dataIndex: 'title', header: '<?php echo Aitsu_Translate :: translate('Title'); ?>', menuDisabled: true, sortable: true},
        {dataIndex: 'organizer', header: '<?php echo Aitsu_Translate :: translate('Organizer'); ?>', width: 50, menuDisabled: true, sortable: true},
        {dataIndex: 'starttime', header: '<?php echo Aitsu_Translate :: translate('Start'); ?>', width: 60, renderer: Ext.util.Format.dateRenderer('d.m.Y H:i:s')},
        {dataIndex: 'endtime', header: '<?php echo Aitsu_Translate :: translate('End'); ?>', width: 60, renderer: Ext.util.Format.dateRenderer('d.m.Y H:i:s')}
    ],
    viewConfig: {
        forceFit: true,
        autoFill: true
    },
	listeners: {
		render: {
			fn: function(){
				this.getStore().load();
			}
		},
            celldblclick: function(grid, rowIndex) {
			editEvent(this.getStore().getAt(rowIndex).get('idevent'));
		},
		rowcontextmenu: function(grid, rowIndex, event) {
                
                    var record = this.getStore().getAt(rowIndex);
                
                    var menu = new Ext.menu.Menu();
			
                    menu.addItem({
                        text: '<?php echo $this->translate('edit Event'); ?>',
                        iconCls: 'edit',
                        handler: function() {
                            editEvent(record.get('idevent'));
                        }
                    });
                    
                    menu.addItem({
                        text: '<?php echo $this->translate('activate Event'); ?>',
                        iconCls: 'cm-setonline',
                        handler: function() {
                            Ext.MessageBox.show({
                            title: '<?php echo $this->translate('Activate event'); ?>',
                            msg: '<?php echo $this->translate('Are you sure to activate the selected event?'); ?>',
                            buttons: Ext.MessageBox.YESNO,
                            fn: function(result) {
                                if (result == 'yes') {
                                    Ext.Ajax.request({
                                        url: '<?php echo $this->url(array('area' => 'management', 'plugin' => 'events', 'paction' => 'activate'), 'plugin'); ?>',
                                        success: function(response, opts) {
                                            var rsp = Ext.decode(response.responseText);
                                            if (rsp.success) {
                                                Ext.aitsu.msg('<?php echo Aitsu_Translate :: translate('Event activated'); ?>', '<?php echo Aitsu_Translate :: translate('The selected event has been activated.'); ?>');
                                                grid.getStore().load(); 
                                            }
                                        },
                                        params: {
                                            idevent: record.get('idevent')
                                        }
                                    });					 			
                                }
                            }
                        });			 			         
                    }
                });
                    
                    menu.addItem({
                        text: '<?php echo $this->translate('delete Event'); ?>',
                        iconCls: 'delete',
                        handler: function() {
                            Ext.MessageBox.show({
                        title: '<?php echo $this->translate('Delete event'); ?>',
                        msg: '<?php echo $this->translate('Are you sure to delete the selected event?'); ?>',
			buttons: Ext.MessageBox.YESNO,
			fn: function(result) {
                            if (result == 'yes') {
                                Ext.Ajax.request({
                                    url: '<?php echo $this->url(array('area' => 'management', 'plugin' => 'events', 'paction' => 'delete'), 'plugin'); ?>',
				    success: function(response, opts) {
                                        var rsp = Ext.decode(response.responseText);
				        if (rsp.success) {
                                            Ext.aitsu.msg('<?php echo Aitsu_Translate :: translate('Event removed'); ?>', '<?php echo Aitsu_Translate :: translate('The selected event has been removed.'); ?>');
                                             grid.getStore().load(); 
				        }
				    },
				    params: {
                                        idevent: record.get('idevent')
                                    }
				});					 			
                            }
                        }
                    });	
                        }
                    });
						
                    menu.showAt(event.getXY());
		}
	},
	plugins: eventExpander
});

dashboard.add({
	columnWidth: 1/3,
	baseCls:'x-plain',
	bodyStyle:'padding:6px 4px 0 4px',
	items: {
		unstyled: false,
		height: 370,
		layout: 'fit',
		items: events
	}
});
