<!-- Standard -->
<div class="docs section-container accordion" data-section data-options="deep_linking: false">
    <?php foreach ($this->nav as $cat) : $cat = (object) $cat; ?>
    <section class="section <?php if ($cat->isCurrent || $cat->isParent) {
        echo 'active';
    } ?>">
    <p class="title">
        <a href="{ref:idcat-<?php echo $cat->idcat; ?>}"><?php echo $cat->name; ?></a>
    </p>

    <?php if ($cat->haschildren) : ?>
    <div class="content">
        <ul class="side-nav">
            <li>
                <a href="{ref:idcat-<?php echo $cat->idcat; ?>}"><?php echo $cat->name; ?></a>
            </li>
            <?php foreach ($cat->children as $child) : ?>
            <li>
                <a href="{ref:idcat-<?php echo $child->idcat; ?>}"><?php echo $child->name; ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
</section>
<?php endforeach; ?>
</div>