{
    region: 'south',
    split: true,
    height: 28,
    minHeight: 28,
    maxHeight: 28,
    margins: '0 0 0 0',
    bbar: new Ext.ux.StatusBar({
        id: 'basic-statusbar',
        defaultText: '',
        text: '',
        iconCls: 'x-status-valid',
        items: [{
            xtype: 'tbtext',
            id: 'session-clock',
            text: ''
        },
        '<a href="http://www.moraso-cms.de" target="_blank">moraso cms</a> <?= Moraso_Status::version(); ?>',
        '-',
        '<a href="https://bitbucket.org/webtischlerei/moraso-cms" target="_blank">aktuelle Version</a> <?= Moraso_Status::latestVersion(); ?>',
        '-',
        'powered by <a href="http://www.aitsu.org" target="_blank">aitsu CMSF</a> <?= Aitsu_Application_Status::version(); ?>',
        '-',
        '&copy; 2013 <a href="http://www.webtischlerei.de" target="_blank">webtischlerei</a>',
        '-',
        'Mit ♥ programmiert in <a href="http://de.wikipedia.org/wiki/Hoya" target="_blank">Hoya</a>'
	]
    })                
}