<form id="filter_events" method="post" action="<?php echo $this->currentUrl; ?>" enctype="multipart/form-data">

    <fieldset>
        <legend>Filter</legend>

        <select id="select_category" name="filter[idcategory]">
            <option value="0">--- select category ---</option>
            <?php foreach ($this->categories as $category) : ?>
                <option<?php echo ($this->filter->idcategory == $category['idcategory'] ? ' selected="selected"' : ''); ?> value="<?php echo $category['idcategory']; ?>"><?php echo $category['name']; ?></option>
            <?php endforeach; ?>
        </select>

        <select id="select_year" name="filter[year]">
            <option value="0">--- select year ---</option>
            <?php foreach ($this->years as $year) : ?>
                <option<?php echo ($this->filter->year == $year ? ' selected="selected"' : ''); ?> value="<?php echo $year; ?>"><?php echo $year; ?></option>
            <?php endforeach; ?>
        </select>

        <select id="select_month" name="filter[month]">
            <option value="0">--- select month ---</option>
            <?php foreach ($this->months as $key => $month) : ?>
                <option<?php echo ($this->filter->month == $key ? ' selected="selected"' : ''); ?> value="<?php echo $key; ?>"><?php echo $month; ?></option>
            <?php endforeach; ?>
        </select>

        <select id="select_day" name="filter[day]">
            <option value="0">--- select day ---</option>
            <?php foreach ($this->days as $day) : ?>
                <option<?php echo ($this->filter->day == $day ? ' selected="selected"' : ''); ?> value="<?php echo $day; ?>"><?php echo $day; ?></option>
            <?php endforeach; ?>
        </select>
    </fieldset>

    <input type="submit" value="filtern" />
</form>

<div id="events">
    <h2>Veranstaltungen</h2>
    <?php foreach ($this->events as $event) : $event = (object) $event; ?>
        <div class="event_item">
            <h3><?php echo $event->category_name; ?></h3>
            <h4><?php echo $event->title; ?></h4>

            <p><?php echo $event->text; ?><br />
                <br />
                <?php echo $event->name; ?><br />
                <?php echo $event->phone; ?><br />
                <a href="mailto:<?php echo $event->email; ?>"><?php echo $event->email; ?></a><br />
                <a href="<?php echo $event->homepage; ?>"><?php echo $event->homepage; ?></a>
            </p>

            <?php if (isset($event->media)) : ?>
                <ul class="file_list">
                    <?php foreach ($event->media as $media) : ?>
                        <li><a href="/file/download/<?php echo $media['idart']; ?>/<?php echo $media['filename']; ?>"><?php echo $media['name']; ?></a></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>

            <p>
                <?php if ($event->startdate == $event->enddate) : ?>
                    am <?php echo $event->startdate; ?>
                <?php else : ?>
                    vom <?php echo $event->startdate; ?> bis <?php echo $event->enddate; ?>
                <?php endif; ?>
            </p>

            <p>
                <?php if ($event->starttime != '00:00' && $event->endtime != '00:00') : ?>
                    <?php if ($event->starttime == $event->endtime) : ?>
                        <?php if ($event->startdate == $event->enddate) : ?>
                            ab <?php echo $event->starttime; ?>
                        <?php else : ?>
                            von <?php echo $event->starttime; ?> bis <?php echo $event->endtime; ?>
                        <?php endif; ?>
                    <?php else : ?>
                        von <?php echo $event->starttime; ?> bis <?php echo $event->endtime; ?>
                    <?php endif; ?>
                <?php endif; ?>
            </p>

        </div>
    <?php endforeach; ?>
</div>
