var center = Ext.getCmp('viewport-center');
center.removeAll();

var assetsPluginTabs = new Ext.TabPanel({
    id: 'assets-plugin-tabs',
    resizeTabs: false,
    minTabWidth: 115,
    tabWidth:135,
    enableTabScroll:true,
    defaults: {
        autoScroll:true
    },
    tabPosition: 'top'
});

center.add(assetsPluginTabs);
	
Ext.getCmp('viewport').doLayout();

Ext.getCmp('assets-plugin-tabs').add({
    title: '<?php echo Aitsu_Translate :: translate('Overview'); ?>',
    layout: 'border',
    items: [{
        region: 'center',
        id: 'assets-plugin-center',
        split: true,
        layout: 'fit'
    }]
});
         
Ext.aitsu.load(['<?php echo $this->url(array('paction' => 'overview')); ?>'], function() {
    assetsPluginTabs.setActiveTab(0);
    assetsPluginTabs.doLayout();
});